output_dir: train_results/pns-corrupt/
tensorboard_output_dir: runs/pns-corrupt/

epochs: 30
threshold: 1.0

optimizer:
  type: Adam
  momentum: 0.9
  learning_rate: 0.0001
  weight_decay: 0.0001

model:
  is_hierarchical: True
  num_features: 15 
  nhid: 256
  num_classes: 2
  pooling_ratio: 0.75
  dropout_ratio: 0.7
  use_edge_attr: True

contrast:
    end_epoch: 0
    aug1: TrackHitDropping
    aug1_param: [0.05, 0.05, 0.1, 0.1]
    aug2: BackgroundTrackDropping
    aug2_param: 0.2
    ce_weight: 10
    use_extra_pos: True
    loss:
        temperature: 0.8

data:
        name: trkvec
        input_dir: /largehome/giorgian/data/parsed_noempty_trkvec/Background/
        input_dir2: /largehome/giorgian/data/parsed_noempty_trkvec/Signal/
        use_momentum: False
        use_energy: False
        n_train: 541693
        n_valid: 135433
        batch_size: 32
        n_workers: 4
        n_folders: 2
        n_workers: 4
        n_folders: 2
        load_complete_graph: False
        corruption_level: 0.05
