output_dir: train_results/particlenet-laplace/
tensorboard_output_dir: runs/particlenet-laplace/
epochs: 10

optimizer:
  type: Adam
  momentum: 0.9
  weight_decay: 0.0001
  learning_rate: 0.001

model:
  type: particlenet-laplace
  hidden_dim: 20
  hidden_activation: Tanh
  layer_norm: True
  affinity_loss: True
  affinity_loss_CE_weight: 1
  affinity_loss_Lp_weight: 0.000001
  affinity_loss_11_weight: 0.000001
  affinity_loss_frobenius_weight: 0.000001
  d_metric: intertrack #einsum
  k: 15
  GNN_config:
    hidden_dim: 64
    hidden_activation: Tanh
    layer_norm: True
    n_graph_iters: 3

data:
        name: trkvec
        input_dir: /largehome/giorgian/data/parsed_noempty_trkvec/Background/
        input_dir2: /largehome/giorgian/data/parsed_noempty_trkvec/Signal/
        n_train: 541 #693
        n_valid: 135 #433
        batch_size: 32
        load_complete_graph: False
