model_name: Dense_GNN_Diffpool
output_dir: results/Dense_GNN_Diffpool/scaled_hits/test
epochs: 200

model:
  hidden_dim: 32
  hidden_activation: Tanh
  layer_norm: True
  learning_rate: 0.0005
  lr_scheduler_decrease_rate: 0.99
  GNN_config:
    hidden_dim: 8
    hidden_activation: Tanh
    layer_norm: True
    n_graph_iters: 3
    # edgenet: False
  diff_pool_config:
    max_num_nodes: 100
    hidden_dim: 8
    embedding_dim: 8
    label_dim: 1
    num_layers: 2
    num_pooling: 2
    assign_hidden_dim: 8
    assign_ratio: 0.2
    linkpred: False

data:
    name: hits_loader
    input_dir: ../prepare/scaled_hits_data/trigger-event
    # input_dir: ../prepare/scaled_hits_data/nontrigger-event/NN
    n_train: 20000 # 000 
    n_valid: 10000 # 00
    real_weight: 1
    false_weight: 1
    batch_size: 1
    n_input_dir: 2
    input_dir2: ../prepare/scaled_hits_data/nontrigger-event/NN
    # input_dir3: ../prepare/hits_data/nontrigger-event/ND
    random_permutation: True
    n_train2: 20000 # 000 #00
    n_valid2: 10000 # 00 #00
    n_train3: 100 #00
    n_valid3: 100 #00