model_name: Diffpool
output_dir: results/Diffpool/scaled_hits/pool2_NN_trigger_1
epochs: 500

model:
  hidden_dim: 60
  hidden_activation: Tanh
  layer_norm: True
  learning_rate: 0.0005
  lr_scheduler_decrease_rate: 0.995
  diff_pool_config:
    max_num_nodes: 400
    hidden_dim: 16
    embedding_dim: 8
    label_dim: 1
    num_layers: 3
    num_pooling: 2
    assign_hidden_dim: 8
    assign_ratio: 0.25
    linkpred: False

data:
    name: hits_loader
    input_dir: /home/tingting/prepare/scaled_hits_data/trigger-event
    # input_dir: ../prepare/scaled_hits_data/nontrigger-event/NN
    n_train: 200000 # 000 
    n_valid: 10000 # 00
    real_weight: 1
    false_weight: 1
    batch_size: 100
    n_input_dir: 2
    input_dir2: /home/tingting/prepare/scaled_hits_data/nontrigger-event/NN
    # input_dir3: ../prepare/hits_data/nontrigger-event/ND
    random_permutation: True
    n_train2: 200000 # 000 #00
    n_valid2: 10000 # 00 #00
    n_train3: 100 #00
    n_valid3: 100 #00