#output_dir: train_results/garnet-physics/
#tensorboard_output_dir: runs/garnet-physics/

epochs: 50
optimizer:
  type: Adam
  momentum: 0.9
  learning_rate: 0.0001
  weight_decay: 0.0001

model:
  num_features: 29 # raw track features + physics
  layers_spec: [[64, 8], [128, 16], [64, 8]]
  num_classes: 2
  potential: garnet

physics_model:
  n_features: 29 # hits + estimated radius + geometric features
  n_hidden: 4
  hidden_size: 8
  hidden_activation: ReLU


data:
        name: trkvec-ecml
        train_input_dir: /home/giorgian/data/presplit/train_gt
        valid_input_dir: /home/giorgian/data/presplit/valid_gt
        test_input_dir: /home/giorgian/data/presplit/test_gt
        n_train: 1000000
        n_valid: 400000
        n_test: 400000
        add_geo_features: True
        use_radius: True

        use_momentum: False
        use_energy: False
        batch_size: 32
        n_workers: 4
        load_complete_graph: False
