model_name: GNNPairDiffpool_affinityloss
output_dir: results/GNNPairDiffpool_affinityloss/scaled_hits/test
epochs: 500

model:
  hidden_dim: 20
  hidden_activation: Tanh
  layer_norm: True
  learning_rate: 0.0005
  lr_scheduler_decrease_rate: 0.99
  affinity_loss: True
  affinity_loss_CE_weight: 0.001
  affinity_loss_Lp_weight: 10
  GNN_config:
    hidden_dim: 8
    hidden_activation: Tanh
    layer_norm: True
    n_graph_iters: 3
    # edgenet: False
  diff_pool_config:
    max_num_nodes: 20
    hidden_dim: 8
    embedding_dim: 8
    label_dim: 1
    num_layers: 2
    num_pooling: 1
    assign_hidden_dim: 8
    assign_ratio: 0.15
    linkpred: False

data:
    name: hits_loader
    input_dir: ../prepare/scaled_hits_data/trigger-event
    # input_dir: ../prepare/scaled_hits_data/nontrigger-event/NN
    n_train: 500 # 00 #000 # 000 
    n_valid: 100 # 00 #00 # 00
    real_weight: 1
    false_weight: 1
    batch_size: 300
    n_input_dir: 2
    input_dir2: ../prepare/scaled_hits_data/nontrigger-event/NN
    # input_dir3: ../prepare/hits_data/nontrigger-event/ND
    random_permutation: True
    n_train2: 500 #00 #000 # 000 #00
    n_valid2: 100 #00 #00 # 00 #00
    n_train3: 100 #00
    n_valid3: 100 #00