output_dir: train_results/pns/

epochs: 50
checkpoint_file_pnl: '/home1/giorgian/projects/ecml-publish/train_results/cached-models/pnet/checkpoints/model_checkpoint_045.pth.tar'

threshold: 1.0

optimizer:
  type: Adam
  momentum: 0.9
  learning_rate: 0.0001
  weight_decay: 0.0001

adj_model:
  num_features: 15
  type: particlenet-laplace
  hidden_dim: 20
  hidden_activation: Tanh
  layer_norm: True
  affinity_loss: True
  affinity_loss_CE_weight: 1
  affinity_loss_Lp_weight: 0.000001
  affinity_loss_11_weight: 0.000001
  affinity_loss_frobenius_weight: 0.000001
  d_metric: intertrack #einsum
  k: 15
  GNN_config:
    hidden_dim: 64
    hidden_activation: Tanh
    layer_norm: True
    n_graph_iters: 3


model:
  is_hierarchical: True
  num_features: 15
  nhid: 256
  num_classes: 2
  pooling_ratio: 0.75
  dropout_ratio: 0.7
  use_edge_attr: True

data:
        name: trkvec-ecml
        train_input_dir: /home/giorgian/data/presplit/train_gt
        valid_input_dir: /home/giorgian/data/presplit/valid_gt
        test_input_dir: /home/giorgian/data/presplit/test_gt
        n_train: 1000000
        n_valid: 400000
        n_test: 400000
        add_geo_features: True
        use_radius: True

        batch_size: 32
        n_workers: 4
        load_complete_graph: False
