output_dir: train_results/set/
tensorboard_output_dir: runs/set/

name_on_wandb: transset-gttrack-fixerror
epochs: 50

optimizer:
  type: Adam
  momentum: 0.9
  learning_rate: 0.0001
  weight_decay: 0.0001

model:
  dim_input: 28
  num_outputs: 1
  dim_output: 2
  num_inds: 32
  dim_hidden: 128
  num_heads: 4
  ln: False

data:
        name: trkvec
        input_dir: /home1/tingtingxuan/Data/parsed_trackvec/Signal
        input_dir2: /home1/tingtingxuan/Data/parsed_trackvec/Background
        use_radius: False
        use_momentum: False
        use_energy: False
        momentum_disturb: 0
        radius_disturb: 0
        n_train: 500000 #693
        n_valid: 100000 #433
        batch_size: 32
        n_workers: 8
        n_folders: 2
        n_folders: 2
        load_complete_graph: False
        add_geo_features: True
