output_dir: train_results/set/
tensorboard_output_dir: runs/set/

name_on_wandb: transset-gttrack-ecml
epochs: 10

optimizer:
  type: Adam
  momentum: 0.9
  learning_rate: 0.0001
  weight_decay: 0.0001

model:
  dim_input: 28
  num_outputs: 1
  dim_output: 2
  num_inds: 32
  dim_hidden: 128
  num_heads: 4
  ln: True


data:
        name: trkvec-ecml
        train_input_dir: /home/giorgian/data/presplit/train_gt
        valid_input_dir: /home/giorgian/data/presplit/valid_gt
        test_input_dir: /home/giorgian/data/presplit/test_gt
        n_train: 10000 #0
        n_valid: 4000 #00
        n_test: 4000  #00
        add_geo_features: True
        use_radius: True

        batch_size: 32
        n_workers: 4
        load_complete_graph: False
