output_dir: train_results/physics/

epochs: 10

optimizer:
  type: Adam
  momentum: 0.9
  learning_rate: 0.0001
  weight_decay: 0.0001

model:
  n_features: 15
  n_hidden: 4
  hidden_size: 256
  hidden_activation: ReLU

loss:
  type: mse

data:
        name: trkvec-ecml
        train_input_dir: /home/giorgian/data/presplit/train_gt
        valid_input_dir: /home/giorgian/data/presplit/valid_gt
        test_input_dir: /home/giorgian/data/presplit/test_gt
        n_train: 10000 #00
        n_valid: 40000 #0
        n_test: 40000 #0
        add_geo_features: True
        use_radius: True

        batch_size: 32
        n_workers: 4
        load_complete_graph: False
