model_name: ParticleNetGeometric
output_dir: results/ParticleNetGeometric/0/
epochs: 500

model:
  final_pooling: meanmax
  conv_params:
    - mlp: [32, 32, 32]
      activation: ReLU
      pooling: mean
    - mlp: [64, 64, 64]
      activation: ReLU
      pooling: mean
    - mlp: [128, 128, 128]
      activation: ReLU
      pooling: mean
  mlp_params: [[32, 0.1], [32, 0.1], [32, 0.1]]
  input_dim: 4
  learning_rate: 0.001

data:
    name: hits_loader
    input_dir: ../prepare/scaled_hits_data/trigger-event
    # input_dir: ../prepare/scaled_hits_data/nontrigger-event/NN
    n_train: 200000 # 000 # 000 
    n_valid: 10000 # 00
    real_weight: 1
    false_weight: 1
    batch_size: 128
    n_input_dir: 2
    input_dir2: ../prepare/scaled_hits_data/nontrigger-event/NN
    # input_dir3: ../prepare/hits_data/nontrigger-event/ND
    random_permutation: True
    n_train2: 200000 #000 # 000 #00
    n_valid2: 10000 # 00 #00
    n_train3: 100 #00
    n_valid3: 100 #00

    #data:
    #    name: hitgraphs_sparse
    #    n_folders: 2
    #    input_dir: /largehome/giorgian/data/parsed_In_Iteration6
    #    n_train: 55868
    #    n_valid: 13967
    #    real_weight: 1
    #    batch_size: 128
    #    input_dir2: /largehome/giorgian/data/parsed_D0_Iteration6
