output_dir: train_results/garnet/
tensorboard_output_dir: runs/garnet/

name_on_wandb: garnet

epochs: 100
optimizer:
  type: Adam
  momentum: 0.9
  learning_rate: 0.0001
  weight_decay: 0.0001

model:
  num_features: 28 # raw track features
  layers_spec: [[64, 8], [128, 16], [64, 8]]
  num_classes: 2

data:
        name: trkvec_predicted
        input_dir: /home1/tingtingxuan/Data/predicted_track_7layer_with_momentum_large/trigger
        input_dir2: /home1/tingtingxuan/Data/predicted_track_7layer_with_momentum_large/non-trigger
        use_radius: False
        use_momentum: False
        use_energy: False
        # momentum_disturb: 0
        # radius_disturb: 0
        n_train: 500000 #693
        n_valid: 100000 #433
        batch_size: 16
        n_workers: 8
        n_folders: 2
        n_folders: 2
        load_complete_graph: False
